### ISSUE TITLE
basic usage of miniRtspServer

### ISSUE THREAD

**Issue by xueshenan** [TaoistLuo/miniRtspServer#1]
I want to use the miniRtspServer for test rtsp stream.
1. Use cmake to compile the project and can found the binary file in the bin directory;
2. Lunch the **rtspserverTest** without no param;
3. Use the vlc to play the rtsp stream with url:rtsp://127.0.0.1:8554/lsl;
4. The **rtspServerText** cannot handle the request and just core dumped;
The following is the lunch log for **rtspServerTest**:
```Shell
 ./rtspserverTest
01-22 10:12:53.065 D RTSP: [H264FileMediaSource:50] "Open file successful \n"
01-22 10:12:53.065 D RTSP: [listen:59] "listen ok\n"
01-22 10:12:53.065 D RTSP: [doClient:130] "create doClient thread ok\n"
01-22 10:12:53.065 D RTSP: [start:51] "TCP server start successfull\n"
01-22 10:12:53.066 D RTSP: [acceptthread:106] "Start do loop\n"
01-22 10:13:00.081 D RTSP: [handleNewConnection:52] "New client connet\n"
01-22 10:13:00.081 D RTSP: [handleNewConnection:53] "client IP:　 127.0.0.1 \n"
01-22 10:13:00.081 D RTSP: [handleNewConnection:54] "client port: 56088 \n"
01-22 10:13:00.082 D RTSP: [handleNewConnection:55] "client fd :  5 \n"
01-22 10:13:00.082 D RTSP: [TcpConnect:36] "Start constructor TcpConnect\n"
01-22 10:13:00.082 D RTSP: [start:159] "create envenTask thread ok\n"
01-22 10:13:00.082 D RTSP: [TcpConnect:45] "Start mTcpConnIOEvent successful\n"
01-22 10:13:00.082 D RTSP: [getSocketIp:41] "The peer IP: 127.0.0.1　\n"
01-22 10:13:00.082 D RTSP: [acceptthread:119] "connect to client successful!\n"
01-22 10:13:00.088 D RTSP: [read:46] "receive date start*************************************************\n"
01-22 10:13:00.088 D RTSP: [read:47] "Read data length: 120  data:\nOPTIONS rtsp://127.0.0.1:8554/lsl RTSP/1.0
CSeq: 2
User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)

"
01-22 10:13:00.088 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
01-22 10:13:00.088 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
01-22 10:13:00.088 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl\n"
01-22 10:13:00.088 D RTSP: [handleReadBytes:111] "handle OPTIONS cmd\n"
01-22 10:13:00.088 D RTSP: [handleReadBytes:115] "handle OPTIONS cmd successful\n"
01-22 10:13:00.091 D RTSP: [read:46] "receive date start*************************************************\n"
01-22 10:13:00.091 D RTSP: [read:47] "Read data length: 146  data:\nDESCRIBE rtsp://127.0.0.1:8554/lsl RTSP/1.0
CSeq: 3
User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
Accept: application/sdp

"
01-22 10:13:00.091 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
01-22 10:13:00.091 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
01-22 10:13:00.091 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl\n"
01-22 10:13:00.091 D RTSP: [handleReadBytes:118] "handle DESCRIBE cmd\n"
01-22 10:13:00.091 D RTSP: [generateSDPDescription:125] "sdp:  v=0
o=- 91705889580 1 IN IP4 10.212.141.86
t=0 0
a=control:*
a=type:broadcast
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=framerate:25
a=control:track0
"
01-22 10:13:00.091 D RTSP: [handleReadBytes:123] "handle DESCRIBE cmd successful\n"
01-22 10:13:00.099 D RTSP: [read:46] "receive date start*************************************************\n"
01-22 10:13:00.099 D RTSP: [read:47] "Read data length: 177  data:\nSETUP rtsp://127.0.0.1:8554/lsl/track0 RTSP/1.0
CSeq: 4
User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
Transport: RTP/AVP;unicast;client_port=38514-38515

"
01-22 10:13:00.099 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
01-22 10:13:00.099 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
01-22 10:13:00.099 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl/track0\n"
01-22 10:13:00.099 D RTSP: [parseTransport:316] "handle setup get client port: RTP:38514  RTCP:38515\n"
01-22 10:13:00.099 D RTSP: [parseMediaTrack:335] "handle setup get client trackID:0\n"
01-22 10:13:00.099 D RTSP: [handleReadBytes:126] "handle SETUP cmd\n"
01-22 10:13:00.099 D RTSP: [handleCmdSetup:505] "Transport ovet UDP\n"
01-22 10:13:00.099 D RTSP: [handleCmdSetup:537] "send msg to client:\nRTSP/1.0 200 OK
CSeq: 4
Transport: RTP/AVP;unicast;client_port=38514-38515;server_port=39016-39017
Session: 327b23c6

\n"
01-22 10:13:00.099 D RTSP: [handleReadBytes:130] "handle SETUP cmd successful\n"
01-22 10:13:00.101 D RTSP: [read:46] "receive date start*************************************************\n"
01-22 10:13:00.101 D RTSP: [read:47] "Read data length: 155  data:\nPLAY rtsp://127.0.0.1:8554/lsl RTSP/1.0
CSeq: 5
User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
Session: 327b23c6
Range: npt=0.000-

t_port=38514-38515

"
01-22 10:13:00.101 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
01-22 10:13:00.101 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
01-22 10:13:00.101 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl\n"
01-22 10:13:00.101 D RTSP: [handleReadBytes:133] "handle PLAY cmd\n"
01-22 10:13:00.101 D RTSP: [handleCmdPlay:555] "Play send data:\nRTSP/1.0 200 OK
CSeq: 5
Range: npt=0.000-
Session: 327b23c6; timeout=60

"
[1]    15167 segmentation fault (core dumped)  ./rtspserverTest`
```

**Comment by tuananh-lab** [comment]
> I want to use the miniRtspServer for test rtsp stream.
> 
>     1. Use cmake to compile the project and can found the binary file in the bin directory;
> 
>     2. Lunch the **rtspserverTest** without no param;
> 
>     3. Use the vlc to play the rtsp stream with url:rtsp://127.0.0.1:8554/lsl;
> 
>     4. The **rtspServerText** cannot handle the request and just core dumped;
>        The following is the lunch log for **rtspServerTest**:
> 
> 
> ```shell
>  ./rtspserverTest
> 01-22 10:12:53.065 D RTSP: [H264FileMediaSource:50] "Open file successful \n"
> 01-22 10:12:53.065 D RTSP: [listen:59] "listen ok\n"
> 01-22 10:12:53.065 D RTSP: [doClient:130] "create doClient thread ok\n"
> 01-22 10:12:53.065 D RTSP: [start:51] "TCP server start successfull\n"
> 01-22 10:12:53.066 D RTSP: [acceptthread:106] "Start do loop\n"
> 01-22 10:13:00.081 D RTSP: [handleNewConnection:52] "New client connet\n"
> 01-22 10:13:00.081 D RTSP: [handleNewConnection:53] "client IP:　 127.0.0.1 \n"
> 01-22 10:13:00.081 D RTSP: [handleNewConnection:54] "client port: 56088 \n"
> 01-22 10:13:00.082 D RTSP: [handleNewConnection:55] "client fd :  5 \n"
> 01-22 10:13:00.082 D RTSP: [TcpConnect:36] "Start constructor TcpConnect\n"
> 01-22 10:13:00.082 D RTSP: [start:159] "create envenTask thread ok\n"
> 01-22 10:13:00.082 D RTSP: [TcpConnect:45] "Start mTcpConnIOEvent successful\n"
> 01-22 10:13:00.082 D RTSP: [getSocketIp:41] "The peer IP: 127.0.0.1　\n"
> 01-22 10:13:00.082 D RTSP: [acceptthread:119] "connect to client successful!\n"
> 01-22 10:13:00.088 D RTSP: [read:46] "receive date start*************************************************\n"
> 01-22 10:13:00.088 D RTSP: [read:47] "Read data length: 120  data:\nOPTIONS rtsp://127.0.0.1:8554/lsl RTSP/1.0
> CSeq: 2
> User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
> 
> "
> 01-22 10:13:00.088 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
> 01-22 10:13:00.088 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
> 01-22 10:13:00.088 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl\n"
> 01-22 10:13:00.088 D RTSP: [handleReadBytes:111] "handle OPTIONS cmd\n"
> 01-22 10:13:00.088 D RTSP: [handleReadBytes:115] "handle OPTIONS cmd successful\n"
> 01-22 10:13:00.091 D RTSP: [read:46] "receive date start*************************************************\n"
> 01-22 10:13:00.091 D RTSP: [read:47] "Read data length: 146  data:\nDESCRIBE rtsp://127.0.0.1:8554/lsl RTSP/1.0
> CSeq: 3
> User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
> Accept: application/sdp
> 
> "
> 01-22 10:13:00.091 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
> 01-22 10:13:00.091 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
> 01-22 10:13:00.091 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl\n"
> 01-22 10:13:00.091 D RTSP: [handleReadBytes:118] "handle DESCRIBE cmd\n"
> 01-22 10:13:00.091 D RTSP: [generateSDPDescription:125] "sdp:  v=0
> o=- 91705889580 1 IN IP4 10.212.141.86
> t=0 0
> a=control:*
> a=type:broadcast
> m=video 0 RTP/AVP 96
> c=IN IP4 0.0.0.0
> a=rtpmap:96 H264/90000
> a=framerate:25
> a=control:track0
> "
> 01-22 10:13:00.091 D RTSP: [handleReadBytes:123] "handle DESCRIBE cmd successful\n"
> 01-22 10:13:00.099 D RTSP: [read:46] "receive date start*************************************************\n"
> 01-22 10:13:00.099 D RTSP: [read:47] "Read data length: 177  data:\nSETUP rtsp://127.0.0.1:8554/lsl/track0 RTSP/1.0
> CSeq: 4
> User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
> Transport: RTP/AVP;unicast;client_port=38514-38515
> 
> "
> 01-22 10:13:00.099 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
> 01-22 10:13:00.099 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
> 01-22 10:13:00.099 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl/track0\n"
> 01-22 10:13:00.099 D RTSP: [parseTransport:316] "handle setup get client port: RTP:38514  RTCP:38515\n"
> 01-22 10:13:00.099 D RTSP: [parseMediaTrack:335] "handle setup get client trackID:0\n"
> 01-22 10:13:00.099 D RTSP: [handleReadBytes:126] "handle SETUP cmd\n"
> 01-22 10:13:00.099 D RTSP: [handleCmdSetup:505] "Transport ovet UDP\n"
> 01-22 10:13:00.099 D RTSP: [handleCmdSetup:537] "send msg to client:\nRTSP/1.0 200 OK
> CSeq: 4
> Transport: RTP/AVP;unicast;client_port=38514-38515;server_port=39016-39017
> Session: 327b23c6
> 
> \n"
> 01-22 10:13:00.099 D RTSP: [handleReadBytes:130] "handle SETUP cmd successful\n"
> 01-22 10:13:00.101 D RTSP: [read:46] "receive date start*************************************************\n"
> 01-22 10:13:00.101 D RTSP: [read:47] "Read data length: 155  data:\nPLAY rtsp://127.0.0.1:8554/lsl RTSP/1.0
> CSeq: 5
> User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
> Session: 327b23c6
> Range: npt=0.000-
> 
> t_port=38514-38515
> 
> "
> 01-22 10:13:00.101 D RTSP: [read:48] "receive date end  -------------------------------------------------\n"
> 01-22 10:13:00.101 D RTSP: [handleReadBytes:89] "RTSPconnection read handle\n"
> 01-22 10:13:00.101 D RTSP: [parseRequest1:236] "parse url  IP:127.0.0.1 \n Port:8554\n Name:lsl\n"
> 01-22 10:13:00.101 D RTSP: [handleReadBytes:133] "handle PLAY cmd\n"
> 01-22 10:13:00.101 D RTSP: [handleCmdPlay:555] "Play send data:\nRTSP/1.0 200 OK
> CSeq: 5
> Range: npt=0.000-
> Session: 327b23c6; timeout=60
> 
> "
> [1]    15167 segmentation fault (core dumped)  ./rtspserverTest`
> ```

I also have the same PLAY error problem as you. Do you have any solution?

**Comment by xueshenan** [comment]
use other solution or just write youself.

**Comment by tuananh-lab** [comment]
> use other solution or just write youself.

Do you think this is a good structure to develop an RTSP server for cameras? I'm a beginner so I don't have much knowledge or experience.

**Comment by xueshenan** [comment]
Yeah, in my opinion, this project is much better than live555. But for now the project is not maintained anymore. So the better way is learn this project structure and create your own rtsp server.
If you don't have experience on mulitimedia, you can just use other opensource rtsp project.
